### ISSUE TITLE
permission denied for theme upload

### ISSUE THREAD

**Issue by rvalyi** [shopinvader/docker-locomotive-shopinvader#2]
Hello, when I upload the shopinvader-template with wagon I get mkdir errors such as
```
Permission denied @ dir_s_mkdir - /home/app/webapp/public/sites/5b0db60fb739cc01ffd5d003
```

Even if I create the folder using docker exec, then I get the same kind of error when it tries to create the theme or fonts subfolder or persist the theme files.

It only works if I manually do ```sudo chown -R 9999:9999 data``` from the host. Is there something missing in the doc or in the docker-compose.yml file?

This is on:
```
Ubuntu Bionic 
Docker version 17.05.0-ce, build 89658be
docker-compose version 1.17.0, build ac53b73
```

**Comment by sebastienbeau** [comment]
Fixed in new version  with volume configuration
https://github.com/akretion/shopinvader-deploy/commit/f3f97b829db435018a4f067f5f774e59a37f19ab

**Comment by hparfr** [comment]
I think this issue is still there.

May be we should chown loco public/sites and public/assets

**Comment by sebastienbeau** [comment]
I close it, as I do not have any issue with it
